services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Oveleon\ContaoRecommendationBundle\:
    resource: '../src/'
    exclude: '../src/{Model,DependencyInjection,Util}'
